[Setting]
;
TestCount=187240
CountLog=90
Language=简体中文
;LoadUnit=N
LoadUnit=kN
;采样频率 秒
SampleFrequency=1
;数据刷新频率毫秒ms
DataRefreshFrequency=200
;曲线刷新频率毫秒ms
WaveRefreshFrequency=200
;位移小数位数
numericUpDown_Pos=2
;试验力小数位数
numericUpDown_Load=2
;变形小数位数
numericUpDown_Ext=2

[Device]
;DeviceID=E34FC53E376CF4E8E23C659CFB5678A3
DeviceID=60159047103D8B6BCCE31D6DBE2D1F36
;DeviceID=60159047103D8B6BCCE31D6DBE2D1F36
;DeviceID=01C678FFC0789E41E04B2AA4536FF63A
FunctionId=0

[POS]
;移动方式
MoveCtrl=0
;速度控制
SpeedCtrl=100
;速度单位
SpeedUnit=0
Destnation=0
DestnationUnit=0

[POS_A]
MoveCtrl=0
AccCtrl=10
AccUnit=0
SpeedCtrl=10
SpeedUnit=0
DecCtrl=-10
DecUnit=0
Destnation=5
DestnationUnit=0

[DynCtrl]
StartCtrl=0
StartSpeed=10
StartSpeedUnit=0
MoveCtrl=0
MoveCtrlUnit=0
WaveFrom=0
PeakCtrl=2
PeakCtrlCheck=False
Cycles=1000
FadeInOut=False
OffSet=0
Amplitude=0.1
Frequency=20


[FrmSetChartAxisY]
TimeEnable=1
TimeRange=1
PositionEnable=1
PosRange=1
LoadEnable=0
LoadRange=1
ExtEnable=0
ExtRange=1
CommandEnable=0
CommandRange=5
TimeX_MAX=2
TimeX_MIN=0
PositionY_MAX=0.2
PositionY_MIN=-0.2
LoadY_MAX=20
LoadY_MIN=-20
ExtY_MAX=20
ExtY_MIN=-20
CommandY_MAX=-20
CommandY_MIN=-20

[FrmSystemSetting]
限位保护选项=0
位移峰值外保护=1
位移峰值外保护生效=0
位移谷值外保护=-1
位移谷值外保护生效=0
位移峰值内保护=0.5
位移峰值内保护生效=0
位移谷值内保护=-0.6
位移谷值内保护生效=0
试验力峰值外保护=10
试验力峰值外保护生效=0
试验力谷值外保护=-5
试验力谷值外保护生效=0
试验力峰值内保护=6
试验力峰值内保护生效=0
试验力谷值内保护=-2
试验力谷值内保护生效=0
变形峰值外保护=3
变形峰值外保护生效=0
变形谷值外保护=-3
变形谷值外保护生效=0
变形峰值内保护=1
变形峰值内保护生效=0
变形谷值内保护=-1
变形谷值内保护生效=0
[SysProtectSetting]
OverLoadPercent_Flag=0
OverLoad_Percent=0
OverLoadForce_Flag=0
OverLoad_Force=0

[PushButtonFunctionConstant]
Up =0.5
HurryUp =100
Down =1
HurryDown =50
[UIDefault]
cbX_ProtectOption=1
comboBoxEx_MaxForce=1
comboBoxEx_MaxTrip=0
comboBoxEx_TripSensor=0
comboBoxEx_ForceUnit=0

[CompanyInfo]
name = 济南新测仪器有限公司

[SoftWareInfo]
Name= 电液伺服疲劳试验机
[AppOpenIndex]
Today=2025-08-20
IndexVal=35
