[Setting]
;
TestCount=1
CountLog=90
Language=简体中文
;LoadUnit=N
LoadUnit=kN

[Device]
DeviceID=6EE5AC5D6083E583ABAE9E8233105A7B
FunctionId=0


[POS]
;移动方式
MoveCtrl=0
;速度控制
SpeedCtrl=10
;速度单位
SpeedUnit=0
Destnation=200
DestnationUnit=0

[POS_A]
MoveCtrl=0
AccCtrl=10
AccUnit=0
SpeedCtrl=10
SpeedUnit=0
DecCtrl=-10
DecUnit=0
Destnation=5
DestnationUnit=0

[DynCtrl]
StartCtrl=0
StartSpeed=10
StartSpeedUnit=0
MoveCtrl=0
MoveCtrlUnit=0
WaveFrom=0
PeakCtrl=2
PeakCtrlCheck=False
Cycles=60
FadeInOut=False
OffSet=6
Amplitude=3
Frequency=2


[FrmSetChartAxisY]
TimeEnable=1
TimeRange=1
PositionEnable=1
PosRange=5
LoadEnable=0
LoadRange=5
ExtEnable=0
ExtRange=5
CommandEnable=0
CommandRange=5
TimeX_MAX=5
TimeX_MIN=0
PositionY_MAX=100
PositionY_MIN=0
LoadY_MAX=100
LoadY_MIN=0
ExtY_MAX=100
ExtY_MIN=0
CommandY_MAX=100
CommandY_MIN=0

[FrmSystemSetting]
限位保护选项=0
位移峰值外保护=1
位移峰值外保护生效=0
位移谷值外保护=-1
位移谷值外保护生效=0
位移峰值内保护=0.5
位移峰值内保护生效=0
位移谷值内保护=-0.6
位移谷值内保护生效=0
试验力峰值外保护=10
试验力峰值外保护生效=0
试验力谷值外保护=-5
试验力谷值外保护生效=0
试验力峰值内保护=6
试验力峰值内保护生效=0
试验力谷值内保护=-2
试验力谷值内保护生效=0
变形峰值外保护=3
变形峰值外保护生效=0
变形谷值外保护=-3
变形谷值外保护生效=0
变形峰值内保护=1
变形峰值内保护生效=0
变形谷值内保护=-1
变形谷值内保护生效=0
[SysProtectSetting]
OverLoadPercent_Flag=0
OverLoad_Percent=0
OverLoadForce_Flag=0
OverLoad_Force=0

[PushButtonFunctionConstant]
Up =0.5
HurryUp =100
Down =1
HurryDown =50
[UIDefault]
cbX_ProtectOption=1
comboBoxEx_MaxForce=1
comboBoxEx_MaxTrip=0
comboBoxEx_TripSensor=0
comboBoxEx_ForceUnit=0

[CompanyInfo]
name = 济南新测仪器有限公司

[SoftWareInfo]
Name= 电液伺服疲劳试验机
[AppOpenIndex]
