[Setting]
;
TestCount=13192
SaveCountLog=1
CountLog=200
SavePVCountLog=1
PVCountLog=100
Language=简体中文
;LoadUnit=N
LoadUnit=N
;采样频率 秒
SampleFrequency=1
;数据刷新频率毫秒ms
DataRefreshFrequency=200
;曲线刷新频率毫秒ms
WaveRefreshFrequency=1
;位移小数位数
numericUpDown_Pos=3
;试验力小数位数
numericUpDown_Load=3
;变形小数位数
numericUpDown_Ext=3
;启用高压
EnableHigh=0
;启用高压
EnableLow=0

[Device]
;DeviceID=6EE5AC5D6083E583ABAE9E8233105A7B 02137E43
;DeviceID=A1BDAAD1EB945F66CB97193401CEE65C 02139D3E
;DeviceID=60159047103D8B6BCCE31D6DBE2D1F36 02146663
;DeviceID=01C678FFC0789E41E04B2AA4536FF63A 02110EA9
DeviceID=6EE5AC5D6083E583ABAE9E8233105A7B
;DeviceID=60159047103D8B6BCCE31D6DBE2D1F36
;DeviceID=01C678FFC0789E41E04B2AA4536FF63A
FunctionId=0

[POS]
;移动方式
MoveCtrl=0
;速度控制
SpeedCtrl=1
;速度单位
SpeedUnit=0
Destnation=0
DestnationUnit=0

[POS_A]
MoveCtrl=0
AccCtrl=10
AccUnit=0
SpeedCtrl=10
SpeedUnit=0
DecCtrl=-10
DecUnit=0
Destnation=5
DestnationUnit=0

[DynCtrl]
StartCtrl=0
StartSpeed=10
StartSpeedUnit=0
MoveCtrl=0
MoveCtrlUnit=0
WaveFrom=0
PeakCtrl=1
PeakCtrlCheck=False
Cycles=500
FadeInOut=False
OffSet=0
Amplitude=0.5
Frequency=3.3
PeakCtrl=1


[FrmSetChartAxisY]
TimeEnable=1
TimeRange=1
PositionEnable=1
PosRange=2
LoadEnable=1
LoadRange=1
ExtEnable=0
ExtRange=1
CommandEnable=0
CommandRange=5
TimeX_MAX=5
TimeX_MIN=0
PositionY_MAX=100
PositionY_MIN=-100
LoadY_MAX=100
LoadY_MIN=-100
ExtY_MAX=20
ExtY_MIN=-20
CommandY_MAX=20
CommandY_MIN=-20

[FrmSystemSetting]
限位保护选项=0
位移峰值外保护=1
位移峰值外保护生效=0
位移谷值外保护=-1
位移谷值外保护生效=0
位移峰值内保护=0.3
位移峰值内保护生效=0
位移谷值内保护=-0.3
位移谷值内保护生效=0
试验力峰值外保护=60
试验力峰值外保护生效=0
试验力谷值外保护=0
试验力谷值外保护生效=0
试验力峰值内保护=50
试验力峰值内保护生效=0
试验力谷值内保护=10
试验力谷值内保护生效=0
变形峰值外保护=3
变形峰值外保护生效=0
变形谷值外保护=-3
变形谷值外保护生效=0
变形峰值内保护=1
变形峰值内保护生效=0
变形谷值内保护=-1
变形谷值内保护生效=0
[SysProtectSetting]
OverLoadPercent_Flag=0
OverLoad_Percent=0
OverLoadForce_Flag=1
OverLoad_Force=30

[PushButtonFunctionConstant]
Up =0.1
HurryUp =2
Down =0.1
HurryDown =2
[UIDefault]
cbX_ProtectOption=1
comboBoxEx_MaxForce=1
comboBoxEx_MaxTrip=7
comboBoxEx_TripSensor=0
comboBoxEx_ForceUnit=1

[CompanyInfo]
name = 济南新测仪器有限公司

[SoftWareInfo]
Name= 电液伺服疲劳试验机
[AppOpenIndex]
Today=2025-10-14
IndexVal=0

