[Setting]
;环境温度
ReportTitle=阻尼力-位移试验检测报告
;环境温度
EnvironmentTemperature=30℃
;实验温度
ExperimentalTemperature=29℃
;试验设备
TestingEquipment=疲劳试验机
;试样规格
SampleSpecification=123
;采样频率 秒
SampleFrequency=1
;试验人员
Tester=测试人
;审核人员
Auditor=审核员
;控制方式
MoveCtrl=POS
;波形显示
WaveCtrl=COS
;中值
Offset=0
;振幅
Amplitude=1
;频率
Frequency=2

[FrmSetChartAxisY]
TimeEnable=1
TimeRange=1
PositionEnable=1
PosRange=1
LoadEnable=1
LoadRange=1
ExtEnable=0
ExtRange=1
CommandEnable=0
CommandRange=5
TimeX_MAX=5
TimeX_MIN=0
PositionY_MAX=5
PositionY_MIN=-5
LoadY_MAX=100
LoadY_MIN=-100
ExtY_MAX=20
ExtY_MIN=-20
CommandY_MAX=-20
CommandY_MIN=-20

